language: generic
sudo: required
services:
  - docker

script:
  - docker build -t skullcutter02/dreamfund-client ./client
  - docker build -t skullcutter02/dreamfund-api ./api
  - docker build -t skullcutter02/dreamfund-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push skullcutter02/dreamfund-client
  - docker push skullcutter02/dreamfund-api
  - docker push skullcutter02/dreamfund-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dreamfund"
  env: "Dreamfund-env"
  bucket_name: "elasticbeanstalk-us-east-2-740995310974"
  bucket_path: "dreamfund"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY