version: "3"
services:
  redis:
    image: "redis:latest"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/local/app/node_modules
      - ./api:/usr/local/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/local/app/node_modules
      - /usr/local/app/.next
      - ./client:/usr/local/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"